// Update the SMTP mail settings in your .env file.
MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailpace.com
MAIL_PORT=587
MAIL_USERNAME=YOUR_MAILPACE_SERVER_API_TOKEN
MAIL_PASSWORD=YOUR_MAILPACE_SERVER_API_TOKEN
MAIL_ENCRYPTION=tls
